### ISSUE TITLE
Latest build has no version tag

### ISSUE THREAD

**Issue by MTCoster** [articulate/docker-http-to-https#4]
Can we get a version tag for the latest build? At the moment we're using the hash to pin to it; this would make it cleaner.

**Comment by tecnobrat** [comment]
Hey @MTCoster thanks for the report. Looks like we missed creating a release for a version when we swapped to debian / nginx 1.17

I created a new release and docker hub is building the image now, so it will be tagged as `1.0.2`.

Thanks!
